#!/bin/sh
set -eu

case "${1:-}" in
  *Username*|*username*)
    printf '%s\n' oauth2
    ;;
  *Password*|*password*)
    if [ -z "${GITLAB_TOKEN:-}" ]; then
      echo "hollysys-git-askpass error=missing_gitlab_token" >&2
      exit 65
    fi
    printf '%s\n' "$GITLAB_TOKEN"
    ;;
  *)
    exit 1
    ;;
esac
